export const GET_INGREDIENTS_DATA = "GET_INGREDIENTS_DATA";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";

export const CONSTRUCTOR_ADD = "CONSTRUCTOR_ADD";
export const CONSTRUCTOR_DELETE = "CONSTRUCTOR_DELETE";
export const CONSTRUCTOR_RESET = "CONSTRUCTOR_RESET";
export const CONSTRUCTOR_REORDER = "CONSTRUCTOR_REORDER";

export const RESET_INGREDIENT_MODAL = "RESET_INGREDIENT_MODAL";
export const SET_INGREDIENT_MODAL = "SET_INGREDIENT_MODAL";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const RESET_ORDER_MODAL = "RESET_ORDER_MODAL";
export const SET_ORDER_MODAL = "SET_ORDER_MODAL";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER = "GET_USER";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const CHECK_USER_AUTH = "CHECK_USER_AUTH";

export const PASSWORD_FORGOTTEN = "PASSWORD_FORGOTTEN";
export const PASSWORD_RESTORED = "PASSWORD_RESTORED";

export const WS_USER_CONNECT = "WS_USER_CONNECT";
export const WS_ALL_CONNECT = "WS_ALL_CONNECT";
export const WS_USER_SUCCESS = "WS_USER_SUCCESS";
export const WS_ALL_SUCCESS = "WS_ALL_SUCCESS";
export const WS_USER_ERROR = "WS_USER_ERROR";
export const WS_ALL_ERROR = "WS_ALL_ERROR";
export const WS_USER_CLOSED = "WS_USER_CLOSED";
export const WS_ALL_CLOSED = "WS_ALL_CLOSED";
export const WS_USER_ORDERS = "WS_USER_ORDERS";
export const WS_ALL_ORDERS = "WS_ALL_ORDERS";


